name: Testes web CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Executa_Testes_WEB:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instala as Dependencias
        run: npm install
        working-directory: ./web

      - name: Executa os Testes
        run: npm run test:headless
        working-directory: ./web
